<?php 
$this->moduleObj->l('Global Option');
$this->moduleObj->l('Rating success message ');
$this->moduleObj->l('Message when rating duplicate from one ip');
$this->moduleObj->l('Media Option');
$this->moduleObj->l('Primary width');
$this->moduleObj->l('Primary height');
$this->moduleObj->l('Thumbnail width');
$this->moduleObj->l('Thumbnail height');
$this->moduleObj->l('Theme Option');
$this->moduleObj->l('Theme');
$this->moduleObj->l('Display a single article by your way');
$this->moduleObj->l('Show Social Butons');
$this->moduleObj->l('Social Button style');
$this->moduleObj->l('Show Rating');
$this->moduleObj->l('Show Article Info');
$this->moduleObj->l('Show Tags');
$this->moduleObj->l('Show Related Products');
$this->moduleObj->l('Show image gallery');
$this->moduleObj->l('Image Width');
$this->moduleObj->l('Fixed width when display content in front-end');
$this->moduleObj->l('Images Align');
$this->moduleObj->l('Display list of articles');
$this->moduleObj->l('Number of aticles in one page');
$this->moduleObj->l('Introtext Limit');
$this->moduleObj->l('Article Order');
$this->moduleObj->l('Show Category Image');
$this->moduleObj->l('Show Rating');
$this->moduleObj->l('Show Article Info');
$this->moduleObj->l('Rss feed settings');
$this->moduleObj->l('Rss feed limit');
$this->moduleObj->l('Rss Introtext Limit');
$this->moduleObj->l('Item Order');
$this->moduleObj->l('Comment Options');
$this->moduleObj->l('Show comment');
$this->moduleObj->l('Use Captcha');
$this->moduleObj->l('Comments limit');
$this->moduleObj->l('Show Pagination');
$this->moduleObj->l('Pagination Theme');
$this->moduleObj->l('Number of comments in one Page');
$this->moduleObj->l('Allowed comment without verify');
$this->moduleObj->l('When sumbmit a published comment');
$this->moduleObj->l('When sumbmit an Unpublished comment');
$this->moduleObj->l('Uninstall Options');
$this->moduleObj->l('Remove data when uninstall module');
$this->moduleObj->l('Remove configuration when uninstall module');
$this->moduleObj->l('Remove images when uninstall module');
 ?>